flask_api/routes/routes_create.py
from flask import render_template, Blueprint, request, redirect, url_for, flash, jsonify
from flask_api.models.model_motorista import Motorista_create, Motorista_update
from flask_api.models.model_veiculo import Veiculo_create
from flask_api.models.model_viagem import *
from flask_api.repositories.motorista_repo.motorista_repo import *
from flask_api.repositories.manutencao_repo import *
from flask_api.repositories.veiculo_repo.veiculo_repo import *
from flask_api.models.enums import *
import sqlite3
from config import Config
from flask_api.repositories.viagem_repo.viagem_repo import *
from flask_api.repositories.abastecimento_repo.abastecimento_repo import *
from pydantic import ValidationError
from flask_api.models.model_viagem import ViagemCreate
from flask_api.models.model_abastecimento import Abastecimento_create
from flask_api.models.model_manutencao import Manutencao_create
from datetime import datetime
from datetime import date 


bp_routes_create = Blueprint('routes_create', __name__)



@bp_routes_create.route("/viagem")
def forms_viagem():
    return render_template("forms/forms_viagem.html")

@bp_routes_create.route("/motorista/create")
def forms_motorista():
    return render_template("forms/forms.html")



# -------------------- CREATE ROUTES --------------------

# -------------------- CRIAR MOTORISTA --------------------
@bp_routes_create.route("/criar_motorista", methods=["POST"])
def criar_motorista():

    try:
        
        # ---------------- Pegar dados do formulário -----------------
        
        raw_data = {
            "nome": request.form.get("nome"),
            "cpf": request.form.get("cpf"),
            "cat_cnh": request.form.get("cnh"),
            "exp_anos": int(request.form.get("experiencia")),
            "disponibilidade": request.form.get("disponibilidade"),
            "cnh_valido_ate": request.form.get("cnh_valido_ate")
        }

        # ----------Validar com Pydantic Model ------------------
        
        pydantic_data = Motorista_create(**raw_data)

        # --------- Validação adicional: CPF duplicado -------------

        if cpf_existe(pydantic_data.cpf):
            flash("❌ Este CPF já está cadastrado.")
            return redirect("/motorista/create")


        # ---------- Converter data string → date (para evitar qualquer erro de tipagem) ---------


        if isinstance(pydantic_data.cnh_valido_ate, str):
            pydantic_data.cnh_valido_ate = datetime.strptime(
                pydantic_data.cnh_valido_ate, "%Y-%m-%d"
            ).date()

        
        # ------------- 5) Criar objeto de domínio (Motorista) ---------------

        motorista = Motorista(
            id=None,  # será gerado pelo BD
            nome=pydantic_data.nome,
            cpf=pydantic_data.cpf,
            cat_cnh=pydantic_data.cat_cnh,
            exp_anos=pydantic_data.exp_anos,
            disponibilidade=pydantic_data.disponibilidade.value,  # ENUM → string
            cnh_valido_ate=pydantic_data.cnh_valido_ate
        )
        # ----------------- Persistir no Banco de Dados -----------------

        inserir_motorista(motorista)
        flash("✅ Motorista cadastrado com sucesso!")

        return redirect(url_for("routes_index.index"))

    except ValueError as e:
        # ----- erros vindos do domínio (ex: CNH vencida) ----------
        flash(f"❌ Erro de validação: {e}")
        return redirect("/motorista/create")

    except Exception as e:
        print("Erro inesperado:", str(e))
        flash("❌ Ocorreu um erro inesperado.")
        return redirect("/motorista/create")

#---------------------------- CRIAR VEICULO ----------------------------
@bp_routes_create.route("/veiculo/create")
def forms_veiculo():
    return render_template("forms/forms_veiculo.html")


@bp_routes_create.route("/criar_veiculo", methods=["POST"])
def criar_veiculo():
    
    # ------------------- VALIDAÇÃO PLACA -------------------
    placa = request.form.get("placa")

    if not placa:
        flash("❌ Placa não informada.")
        return redirect(url_for("routes_create.forms_veiculo"))
    if validar_placa_mercosul(placa) == False:
        flash("❌ Placa inválida. Use o padrão Mercosul (LLLNLNNN).")
        return redirect(url_for('routes_create.forms_veiculo'))
    if placa_existe(placa):
        flash("❌ Já há um veiculo com essa placa no sistema!")
        return redirect(url_for('routes_create.forms_veiculo'))

    # ------------------- BUSCA ÚNICA DO MODELO -------------------
    try:
        id_modelo = int(request.form.get("modelo_fk"))
    except (ValueError, TypeError):
        flash("❌ ID do Modelo inválido.")
        return redirect(url_for("routes_create.forms_veiculo"))

    # CHAMA A FUNÇÃO ÚNICA
    dados_modelo = buscar_dados_modelo(id_modelo) 
    
    if dados_modelo is None:
        flash("❌ Modelo não encontrado no banco de dados.")
        return redirect(url_for("routes_create.forms_veiculo"))
    
    # Desempacota os dados buscados para a variável 'raw_data'
    # Os dados buscados (tipo_veiculo, qtd_litros, consumo_medio, tipo_combustivel) 
    # sobrescrevem qualquer valor potencial do formulário, garantindo a integridade.
    
    # ------------------- MONTAR OBJETO Pydantic -------------------
    raw_data = {
        'placa': placa,
        'modelo_fk': id_modelo,
        'ano': int(request.form.get("ano")),
        'quilometragem': float(request.form.get("quilometragem")),
        'status': request.form.get("disponibilidade", Veiculo_status.ATIVO.value),
        
        # ------- Dados obtidos do banco (substituem as 4 buscas individuais) --------
        **dados_modelo
    }
    
    if raw_data["quilometragem"] < 0:
        flash("❌ Quilometragem Inválida")
        return redirect(url_for("routes_create.forms_veiculo"))
        

    try:
        data = Veiculo_create(**raw_data)
    except Exception as e:
        flash(f"❌ Erro de validação de dados: {e}")
        return redirect(url_for("routes_create.forms_veiculo"))

    # ------------------- INSERT NO BANCO -------------------
    inserir_veiculo(data)

    flash("✅ Veículo cadastrado com sucesso!")
    return redirect(url_for("routes_index.index"))





@bp_routes_create.route("/criar_viagem", methods=["POST"])
def criar_viagem_route():

    # ---------- Dados do formulário ----------------
    dados = request.form
    placa_fk = dados.get("placa_fk")
    cpf_fk = dados.get("cpf_fk")
    origem = dados.get("origem")
    destino = dados.get("destino")
    distancia_str = dados.get("distancia_km")
    data_chegada = dados.get("data_chegada")

    # ---------------- Validação básica ---------------
    try:
        if not placa_fk or not cpf_fk or not origem or not destino or not distancia_str or not data_chegada:
            raise ValueError("Todos os campos são obrigatórios.")

        distancia_km = float(distancia_str)

    except ValueError as e:
        flash(f"❌ Erro: {str(e)}")
        return redirect(url_for("routes_create.forms_viagem"))

    # -------------- Buscar entidades -------------
    veiculo = repo_get_veiculo(placa_fk)
    if not veiculo:
        flash("❌ Veículo não encontrado.")
        return redirect(url_for("routes_create.forms_viagem"))

    motorista = repo_get_motorista(cpf_fk)
    if not motorista:
        flash("❌ Motorista não encontrado.")
        return redirect(url_for("routes_create.forms_viagem"))

    # -------- Modelo Pydantic ------------
    try:
        viagem = ViagemCreate(
            placa_fk=placa_fk,
            cpf_fk=cpf_fk,
            origem=origem,
            destino=destino,
            distancia_km=distancia_km,
            data_chegada=data_chegada,
        )
    except Exception as e:
        flash(f"❌ Erro nos dados da viagem: {str(e)}")
        return redirect(url_for("routes_create.forms_viagem"))

    # ------- REGRAS DE NEGÓCIO --------------

    # ----------------- Status do motorista ---------------------
    if motorista["DISPONIBILIDADE"] != Status_motorista.ATIVO.value:
        flash("❌ Motorista não está disponível ou sua cnh está vencida.")
        return redirect(url_for("routes_create.forms_viagem"))

    # -------------- Status do veículo ----------------
    if veiculo["STATUS"] != Veiculo_status.ATIVO.value:
        flash("❌ Veículo não está disponível.")
        return redirect(url_for("routes_create.forms_viagem"))
    
    if veiculo["STATUS"] == Veiculo_status.PREVENTIVA_URGENTE.value:
        flash("❌ Veiculo precisa de uma revisão preventiva urgente! ")

    # ------------- Hodômetro atual -------------
    hodometro_atual = repo_get_quilometragem(placa_fk)
    if hodometro_atual is None:
        flash("❌ Erro ao obter quilometragem do veículo.")
        return redirect(url_for("routes_create.forms_viagem"))

    hodometro_final = hodometro_atual + distancia_km

    #--------- Consumo e combustível atual -----------
    consumo_medio, litros_atual = repo_get_consumo(placa_fk)
    litros_necessarios = distancia_km / consumo_medio

    if litros_necessarios > litros_atual:
        flash("❌ Combustível insuficiente para realizar a viagem.")
        return redirect(url_for("routes_create.forms_viagem"))

    novo_nivel_combustivel = litros_atual - litros_necessarios

    #-----------Persistência — todas as operações dentro da mesma transação ------------- 
    try:
        with conectar() as conn:
            # Inserir viagem
            repo_insert_viagem(
                conn,
                viagem,
                hodometro_atual,
                hodometro_final
            )

            # Inserir histórico
            repo_insert_evento_viagem(conn, viagem)

            # Atualizar veículo
            repo_update_veiculo_viagem(
                conn,
                placa_fk,
                hodometro_final
            )

            # Atualizar combustível
            repo_update_combustivel(
                conn,
                placa_fk,
                novo_nivel_combustivel
            )

flask_api/routes/routes_delete.py
from flask import render_template, Blueprint, request, redirect, url_for, flash, jsonify
from flask_api.models.model_motorista import Motorista_create, Motorista_update
from flask_api.models.model_veiculo import Veiculo_create
from flask_api.models.model_viagem import *
from flask_api.repositories.motorista_repo.motorista_repo import *
from flask_api.repositories.manutencao_repo import *
from flask_api.repositories.veiculo_repo.veiculo_repo import *
from flask_api.models.enums import *
import sqlite3
from config import Config
from flask_api.repositories.viagem_repo.viagem_repo import *
from flask_api.repositories.abastecimento_repo.abastecimento_repo import *
from pydantic import ValidationError
from flask_api.models.model_viagem import ViagemCreate
from flask_api.models.model_abastecimento import Abastecimento_create
from flask_api.models.model_manutencao import Manutencao_create
from datetime import datetime
from datetime import date 
from flask_api.models.enums import Motorista_status, Veiculo_status

bp_routes_delete = Blueprint('routes_delete', __name__)
#--------------------- DELETE ROUTES -------------------------------

@bp_routes_delete.route("/motorista/deletar")
def delete_motorista():
    return render_template("delete/deletar_motorista.html")


@bp_routes_delete.route("/deletar_motorista", methods=["POST"])
def deletar_motorista_route():
    try:
        cpf = request.form.get("cpf")
        # Recebe o cpf do formulário e valida se ele existe no Banco de Dados
        if not cpf_existe(cpf):
            flash("❌ Insira um CPF válido para deletar.")
            return redirect("/motorista/deletar")
        
        with sqlite3.connect(Config.DATABASE) as conn:
            cur = conn.cursor()
            
            cur.execute("""
            SELECT DISPONIBILIDADE
            FROM MOTORISTA
            WHERE CPF = ?                        
                        """, (cpf,))
            cpf_status = cur.fetchone()
            
        status = cpf_status[0]  # ← pega o valor real
        
        if status not in (
            Motorista_status.ATIVO.value,
            Motorista_status.INATIVO.value
        ):
            flash("❌ Delete o Motorista apenas se ele não estiver em Viagem")
            return redirect("/motorista/deletar")


# ------------ DELETAR ------------
        motorista_deletado = deletar_motorista(cpf)
        flash("✅ Motorista Deletado com sucesso!")
        return redirect(url_for('routes_index.index'))
        
    except ValueError as e:
        flash(f"❌ Erro de validação: {e}")
        return redirect("/motorista/deletar")

    except Exception as e:
        print(f"Erro inesperado ao deletar motorista: {e}")
        flash("❌ Erro inesperado no sistema.")
        return redirect("/motorista/deletar")
    
@bp_routes_delete.route("/veiculo/deletar")  
def delete_veiculo():
    return render_template("delete/deletar_veiculo.html")

@bp_routes_delete.route("/deletar_veiculo", methods=["POST"])
def deletar_veiculo_route():
    try:
        placa = request.form.get("placa")
        
        if not placa_existe(placa):
            flash("❌ Insira uma PLACA válida para deletar.")
            return redirect("/veiculo/deletar")
        
        with sqlite3.connect(Config.DATABASE) as conn:
            cur = conn.cursor()
            
            cur.execute("""
            SELECT STATUS
            FROM VEICULO
            WHERE PLACA = ?                        
                        """, (placa,))
            placa_status = cur.fetchone()
        
        status = placa_status[0]  # ← pega o valor real
        if status not in (
            Veiculo_status.ATIVO.value,
            Veiculo_status.INATIVO.value
        ):
            flash("❌ Delete o Veículo apenas se ele não estiver em Viagem")
            return redirect("/veiculo/deletar")
        
        veiculo_deletado = deletar_veiculo(placa)
        flash("✅ Veiculo Deletado com sucesso!")
        return redirect(url_for('routes_index.index'))
        
    except ValueError as e:
        flash(f"❌ Erro de validação: {e}")
        return redirect("/veiculo/deletar")

    except Exception as e:
        print(f"Erro inesperado ao deletar veiculo: {e}")
        flash("❌ Erro inesperado no sistema.")
        return redirect("/veiculo/deletar")
    

flask_api/routes/routes_read.py
from flask import render_template, Blueprint, request, redirect, url_for, flash, jsonify
from flask_api.models.model_motorista import Motorista_create, Motorista_update
from flask_api.models.model_veiculo import Veiculo_create
from flask_api.models.model_viagem import *
from flask_api.repositories.motorista_repo.motorista_repo import *
from flask_api.repositories.manutencao_repo import *
from flask_api.repositories.veiculo_repo.veiculo_repo import *
from flask_api.models.enums import *
import sqlite3
from config import Config
from flask_api.repositories.viagem_repo.viagem_repo import *
from flask_api.repositories.abastecimento_repo.abastecimento_repo import *
from pydantic import ValidationError
from flask_api.models.model_viagem import ViagemCreate
from flask_api.models.model_abastecimento import Abastecimento_create
from flask_api.models.model_manutencao import Manutencao_create
from datetime import datetime
from datetime import date 


bp_routes_read = Blueprint('routes_read', __name__)


@bp_routes_read.route("/modelo/read")
def tabela_modelo():
    return render_template("read/ver_modelos.html")

@bp_routes_read.route("/motorista/read")
def tabela_motorista():
    return render_template("read/ver_motorista.html")

@bp_routes_read.route("/veiculo/read")
def tabela_veiculo():
    return render_template("read/ver_veiculo.html")

@bp_routes_read.route("/historico_veiculo/read")
def tabela_historico():
    return render_template("read/ver_historico_veiculo.html")

flask_api/routes/routes_report.py
from flask import render_template, Blueprint, request, redirect, url_for, flash, jsonify
from flask_api.models.model_motorista import Motorista_create, Motorista_update
from flask_api.models.model_veiculo import Veiculo_create
from flask_api.models.model_viagem import *
from flask_api.repositories.motorista_repo.motorista_repo import *
from flask_api.repositories.manutencao_repo import *
from flask_api.repositories.veiculo_repo.veiculo_repo import *
from flask_api.models.enums import *
import sqlite3
from config import Config
from flask_api.repositories.viagem_repo.viagem_repo import *
from flask_api.repositories.abastecimento_repo.abastecimento_repo import *
from pydantic import ValidationError
from flask_api.models.model_viagem import ViagemCreate
from flask_api.models.model_abastecimento import Abastecimento_create
from flask_api.models.model_manutencao import Manutencao_create
from datetime import datetime
from datetime import date 


bp_routes_report = Blueprint('routes_report', __name__)

@bp_routes_report.route("/relatorio/ranking_eficiencia")
def relatorio_eficiencia():
    return render_template("relatorio/relatorio_eficiencia.html")

@bp_routes_report.route("/relatorio/quilometragem_media")
def relatorio_quilometragem():
    return render_template("relatorio/relatorio_km.html")

@bp_routes_report.route("/relatorio/total_viagens")
def relatorio_total_viagens():
    return render_template("relatorio/relatorio_total_viagens.html")

@bp_routes_report.route("/relatorio/custo_manutenções")
def relatorio_manutencao():
    return render_template("relatorio/relatorio_manutencao.html")

flask_api/templates/options/motorista_options.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Menu Motorista</title>
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/index.css')}}"
    />
    <link rel="shortcut icon" href="{{url_for('static', filename='img/truck.svg')}}" type="image/x-icon">

  </head>
  <body>
    {% with messages = get_flashed_messages() %} {% if messages %}
    <div class="flash-messages">
      {% for msg in messages %}
      <div class="flash">{{ msg }}</div>
      {% endfor %}
    </div>
    {% endif %} {% endwith %}
    <h1 class="titulo_principal">SISTEMA DE GERENCIAMENTO DE FROTA</h1>
    <h2 class="subtitulo_principal">Menu Motirista</h2>

    <main class="principal-index">
      <a href="{{url_for('routes_create.forms_motorista')}}" class="card_link">
        <div class="principal_card_person principal_card">
          <img
            class="principal_card_img"
            src="{{url_for('static',filename='img/person.svg')}}"
            alt=""
          />
          <p class="principal_card_name">Cadastrar Motorista</p>
        </div>
      </a>
      <a href="{{url_for('routes_read.tabela_motorista')}} " class="card_link">
        <div class="principal_card_veicle principal_card">
          <img
            class="principal_card_img"
            src="{{url_for('static',filename='img/search.svg')}}"
            alt=""
          />
          <p class="principal_card_name">Ver Motoristas</p>
        </div>
      </a>
      <a href="{{url_for('routes_update.update_motorista')}}" class="card_link">
        <div class="principal_card_report principal_card">
          <img
            class="principal_card_img"
            src="{{url_for('static',filename='img/update.svg')}}"
            alt=""
          />
          <p class="principal_card_name">Atualizar Motorista</p>
        </div>
      </a>
      <a href="{{url_for('routes_delete.delete_motorista')}}" class="card_link">
        <div class="principal_card_history principal_card">
          <img
            class="principal_card_img"
            src="{{url_for('static',filename='img/delete.svg')}}"
            alt=""
          />
          <p class="principal_card_name">Deletar Motorista</p>
        </div>
      </a>
    </main>
  </body>
</html>

flask_api/templates/options/relatorio_options.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Menu Relatórios</title>
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/index.css')}}"
    />
    <link rel="shortcut icon" href="{{url_for('static', filename='img/truck.svg')}}" type="image/x-icon">

  </head>
  <body>
    {% with messages = get_flashed_messages() %} {% if messages %}
    <div class="flash-messages">
      {% for msg in messages %}
      <div class="flash">{{ msg }}</div>
      {% endfor %}
    </div>
    {% endif %} {% endwith %}
    <h1 class="titulo_principal">SISTEMA DE GERENCIAMENTO DE FROTA</h1>
    <h2 class="subtitulo_principal">Menu Relatórios</h2>

    <main class="principal-report">
      <a href="{{url_for('routes_report.relatorio_eficiencia')}}" class="card_link">
        <div class="principal_card_person principal_card">
          <img
            class="principal_card_img"
            src="{{url_for('static',filename='img/person.svg')}}"
            alt=""
          />
          <p class="principal_card_name">Ranking Eficiencia</p>
        </div>
      </a>
      <a href="{{url_for('routes_report.relatorio_total_viagens')}} " class="card_link">
        <div class="principal_card_veicle principal_card card-total-viagens">
          <img
            class="principal_card_img"
            src="{{url_for('static',filename='img/truck.svg')}}"
            alt=""
          />
          <p class="principal_card_name">Total de Viagens</p>
        </div>
      </a>

            <a href="{{url_for('routes_report.relatorio_quilometragem')}} " class="card_link">
      <div class="principal_card_report1 principal_card principal-card-">
        <img
          class="principal_card_img"
          src="{{url_for('static',filename='img/report.svg')}}"
          alt=""
        />
        <p class="principal_card_name km_veiculo">Quilometragem por Veículo</p>
      </div>
      </a>


      <a href="{{url_for("routes_report.relatorio_manutencao")}}" class="card_link">
                <div class="principal_card_report2 principal_card principal-card">
        <img
          class="principal_card_img"
          src="{{url_for('static',filename='img/report.svg')}}"
          alt=""
        />
        <p class="principal_card_name km_veiculo">Relatório Manutenções</p>
      </div>
      </a>
    </main>
  </body>
</html>

flask_api/templates/options/veiculo_options.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Menu Motoristas</title>
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/index.css')}}"
    />
    <link rel="shortcut icon" href="{{url_for('static', filename='img/truck.svg')}}" type="image/x-icon">

  </head>

  <style>
    body{
    height: 122vh;
    

    }

    .principal_card_report{
    height: 27em;  /* ok */
    width: 64.5rem;    /* ocupa toda a célula da grid */
    margin-top: 1rem;
    }

    .principal_card_history{
    height: 25em;  /* ok */
    width: 64.5rem;    /* ocupa toda a célula da grid */
    margin-top: 1rem;
    }
  </style>
  <body>
    {% with messages = get_flashed_messages() %} {% if messages %}
    <div class="flash-messages">
      {% for msg in messages %}
      <div class="flash">{{ msg }}</div>
      {% endfor %}
    </div>
    {% endif %} {% endwith %}
    <h1 class="titulo_principal">SISTEMA DE GERENCIAMENTO DE FROTA</h1>
    <h2 class="subtitulo_principal">Menu Veiculos</h2>

    <main class="principal">
      <a href="{{url_for('routes_create.forms_veiculo')}}" class="card_link">
        <div class="principal_card_person principal_card">
          <img
            class="principal_card_img"
            src="{{url_for('static',filename='img/truck.svg')}}"
            alt=""
          />
          <p class="principal_card_name">Cadastrar Veículo</p>
        </div>
      </a>

      <a href="{{url_for('routes_read.tabela_veiculo')}} " class="card_link">
        <div class="principal_card_veicle principal_card">
          <img
            class="principal_card_img"
            src="{{url_for('static',filename='img/search.svg')}}"
            alt=""
          />
          <p class="principal_card_name">Ver Veículos</p>
        </div>
      </a>

      <a href="{{url_for('routes_delete.delete_veiculo')}}" class="card_link">
        <div class="principal_card_fuel principal_card">
        <img
          class="principal_card_img"
          src="{{url_for('static',filename='img/delete.svg')}}"
          alt=""
        />
        <p class="principal_card_name">Deletar Veículo</p>
      </div>
      </a>

      <a href="{{url_for('routes_create.forms_manutencao')}}" class="card_link">
        <div class="principal_card_maintence principal_card">
          <img
            class="principal_card_img"
            src="{{url_for('static',filename='img/maintence.svg')}}"
            alt=""
          />
          <p class="principal_card_name">Manutenção</p>
        </div>
      </a>

      <a href="{{url_for('routes_create.forms_abastecimento')}}" class="card_link">
        <div class="principal_card_report principal_card">
          <img
            class="principal_card_img"
            src="{{url_for('static',filename='img/fuel.svg')}}"
            alt=""
          />
          <p class="principal_card_name">Abastecimento</p>
        </div>
      </a>


      <a href="{{url_for("routes_read.tabela_historico")}}" class="card_link">
          <div class="principal_card_history principal_card">
        <img
          class="principal_card_img"
          src="{{url_for('static',filename='img/report.svg')}}"
          alt=""
        />
        <p class="principal_card_name">Histórico de Veiculo</p>
      </div>
      </a>
            <a href="{{url_for("routes_update.update_veiculo")}}" class="card_link">
        <div class="principal_card_update principal_card">
        <img
          class="principal_card_img"
          src="{{url_for('static',filename='img/update.svg')}}"
          alt=""
        />
        <p class="principal_card_name">Atualizar Veiculo</p>
      </div>
      </a>
    </main>
  </body>
</html>